### ISSUE TITLE
How do i import it

### ISSUE THREAD

**Issue by Aidan647** [carlos-menezes/worldometers.py#6]
How do i import it???
i tried `import Worldometers` and `import worldometers`

**Comment by InkSlob** [comment]
Good question!  Couldn't figure that out.
Did see some people doing this.
`# Lets get data from that url  
df = pd.read_html('https://www.worldometers.info/coronavirus/#countries')`
[Visualize Coronavirus](https://www.c-sharpcorner.com/article/visualize-corona-cases-in-python/)

**Comment by steunenberg** [comment]
I guess the pd.read_html is for licensed worldometer.info users, I get a 'HTTP 403' error.
It looks like setup.py is not complete (but I'm not anexpert on that, I keep forgetting) so  you have to fix this yourself.
By the way, this script connects to https://countrymeters.info/en and not to www.worldometers.info and there is no covid info on that website.

**Comment by carlos-menezes** [comment]
`import worldometers` should work.
